Repository MaksimPegov/word-cards-service, pull requests merged in 2024-03, with the labels that each got.

#11 Users microservice implementation
  .gitignore
  .idea/compiler.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  README.md
  _db/docker-compose.yml
  _media/db_primary_connection.png
  _media/db_primary_general.png
  _media/db_secondary_connection.png
  _media/db_secondary_general.png
  eureka-server/target/eureka-server-1.0-SNAPSHOT.jar
  eureka-server/target/maven-archiver/pom.properties
  eureka-server/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  eureka-server/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  eureka-server/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  eureka-server/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  pom.xml
  users/Dockerfile
  users/pom.xml
  users/src/main/java/com/maksimpegov/users/UserConfig.java
  users/src/main/java/com/maksimpegov/users/UsersApplication.java
  users/src/main/java/com/maksimpegov/users/UsersController.java
  users/src/main/java/com/maksimpegov/users/UsersService.java
  users/src/main/java/com/maksimpegov/users/exeption/ApiException.java
  users/src/main/java/com/maksimpegov/users/exeption/ApiExceptionHandler.java
  users/src/main/java/com/maksimpegov/users/exeption/ApiRequestException.java
  users/src/main/java/com/maksimpegov/users/models/PasswordEditRequest.java
  users/src/main/java/com/maksimpegov/users/models/UserServiceResponse.java
  users/src/main/java/com/maksimpegov/users/user/User.java
  users/src/main/java/com/maksimpegov/users/user/UserDto.java
  users/src/main/java/com/maksimpegov/users/user/UserInfo.java
  users/src/main/java/com/maksimpegov/users/user/UserMapper.java
  users/src/main/java/com/maksimpegov/users/user/UsersRepository.java
  users/src/main/resources/application.yml
  users/src/main/resources/banner.txt
  users/target/classes/application.yml
  users/target/classes/banner.txt
  users/target/classes/com/maksimpegov/users/UsersApplication.class
  users/target/maven-archiver/pom.properties
  users/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  users/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  users/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  users/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  users/target/users-1.0-SNAPSHOT.jar
  word-cards-service.iml
Labels: Implementation, help wanted

#10 [kafka] Add Kafka infrastructure
  _kafka/.env
  _kafka/README.md
  _kafka/docker-compose.yml
Labels: Implementation

#14 [#12] Use UUID as userID
  users/src/main/java/com/maksimpegov/users/UsersController.java
  users/src/main/java/com/maksimpegov/users/UsersService.java
  users/src/main/java/com/maksimpegov/users/user/User.java
  users/src/main/java/com/maksimpegov/users/user/UsersRepository.java
Labels: refactoring
